// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for author_opinion documents
 */
interface AuthorOpinionDocumentData {
  /**
   * name field in *author_opinion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_opinion.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * bio field in *author_opinion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_opinion.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * avatar field in *author_opinion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author_opinion.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * title field in *author_opinion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_opinion.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * email field in *author_opinion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author_opinion.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * author_opinion document from Prismic
 *
 * - **API ID**: `author_opinion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorOpinionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AuthorOpinionDocumentData>,
    "author_opinion",
    Lang
  >;

/**
 * Item in *blog_post → Tags*
 */
export interface BlogPostDocumentDataTagsItem {
  /**
   * Tag field in *blog_post → Tags*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select a tag
   * - **API ID Path**: blog_post.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tag: prismic.SelectField<
    | "local-news"
    | "capiz-news"
    | "health-wellness"
    | "auto-racing"
    | "fact-check-news"
    | "cebu-news"
    | "negros-news"
    | "medical-frontiers"
    | "travel-destinations"
    | "entertainment"
    | "film-reviews"
    | "music-news"
    | "celebrity-updates"
    | "lifestyle-trends"
    | "fashion-style"
    | "food-dining"
    | "franchise-business"
    | "arts-culture"
    | "therapeutic-arts"
    | "cultural-events"
    | "education-news"
    | "academic-updates"
    | "university-news"
    | "student-life"
    | "teacher-stories"
    | "environment-news"
    | "climate-change"
    | "green-living"
    | "environmental-awareness"
    | "editorial-opinion"
    | "current-events"
    | "politics-news"
    | "special-issues"
    | "foreign-politics"
    | "fashion-trends"
    | "fashion-shopping"
    | "investigative-journalism"
    | "social-impact"
    | "community-building"
    | "advocacy-reporting"
    | "sports-day"
    | "farming-agriculture"
    | "all-sports"
    | "national-news"
    | "business-news"
    | "automotive"
    | "vehicles"
    | "transportation"
    | "technology"
    | "innovations"
    | "gadgets"
    | "company-news"
    | "staff-updates"
    | "contact-info"
  >;

  /**
   * Tag Priority field in *blog_post → Tags*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.tags[].priority
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  priority: prismic.SelectField<"primary" | "secondary" | "tertiary">;
}

/**
 * Content for blog_post documents
 */
interface BlogPostDocumentData {
  /**
   * title field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * summary field in *blog_post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * content field in *blog_post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * featured_image field in *blog_post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * category field in *blog_post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "news"
    | "feature"
    | "opinion"
    | "initiatives"
    | "sports"
    | "business"
    | "other-pages"
  >;

  /**
   * subcategory field in *blog_post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.subcategory
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  subcategory: prismic.SelectField<
    | "local"
    | "fact-first-ph"
    | "capiz"
    | "negros"
    | "health"
    | "travel"
    | "entertainment"
    | "lifestyle"
    | "arts-and-culture"
    | "education"
    | "environment"
    | "editorial"
    | "fashion-fridays"
    | "empower"
    | "global-shapers-iloilo"
    | "zero-day"
    | "local-news"
    | "national-news"
    | "monitoring"
    | "tech-talk"
    | "about-us"
    | "contact-us"
  >;

  /**
   * author field in *blog_post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * published_date field in *blog_post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  published_date: prismic.DateField;

  /**
   * is_featured field in *blog_post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.is_featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField;

  /**
   * updated_date field in *blog_post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.updated_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  updated_date: prismic.DateField;

  /**
   * editors pick field in *blog_post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.editors_pick
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  editors_pick: prismic.BooleanField;

  /**
   * banner pick field in *blog_post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.banner_pick
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  banner_pick: prismic.BooleanField;

  /**
   * Tags field in *blog_post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<BlogPostDocumentDataTagsItem>>;

  /**
   * Estimated Reading Time (minutes) field in *blog_post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Auto-calculated if left empty
   * - **API ID Path**: blog_post.reading_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  reading_time: prismic.NumberField;

  /**
   * Meta Description field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO meta description
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Breaking News field in *blog_post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.is_breaking_news
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_breaking_news: prismic.BooleanField;
}

/**
 * blog_post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

export type AllDocumentTypes = AuthorOpinionDocument | BlogPostDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorOpinionDocument,
      AuthorOpinionDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataTagsItem,
      AllDocumentTypes,
    };
  }
}
