import AutoRefresh from "@/components/AutoRefresh";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import LoadingScreen from "@/components/LoadingScreen";
import NavigationBar from "@/components/Navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { getLayoutPosts } from "../../lib/wordpress";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Daily Guardian | We Write, You Decide",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await getLayoutPosts();

  // Latest local+featured post for breaking news, fallback to any featured
  const breakingPost =
    posts.find((p) => p.data.subcategory === "local" && p.data.is_featured) ||
    posts.find((p) => p.data.is_featured) ||
    posts[0] ||
    null;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Runs synchronously before React — blocks page on first visit with no flash */}
        <script dangerouslySetInnerHTML={{ __html: `try{if(!sessionStorage.getItem('dg_intro'))document.documentElement.classList.add('dg-first-load')}catch(e){}` }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        <LoadingScreen />
        <AutoRefresh intervalMs={60_000} />
        <Header posts={posts} breakingPost={breakingPost} />
        <NavigationBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
