import AutoRefresh from "@/components/AutoRefresh";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import LoadingScreen from "@/components/LoadingScreen";
import NavigationBar from "@/components/Navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Script from "next/script";
import {
  getAllPosts,
  getLayoutPosts,
  getPostsByCategorySlugs,
} from "../../lib/wordpress";
import "./globals.css";

export const revalidate = 60;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Daily Guardian | We Write, You Decide",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [
    posts,
    recentNav,
    sportsNav,
    voicesNav,
    businessNav,
    featuresNav,
    initiativesNav,
  ] = await Promise.all([
    getLayoutPosts(),
    getAllPosts(20),
    getPostsByCategorySlugs(["sports"], 4),
    getPostsByCategorySlugs(["voices", "visons", "opinion"], 4),
    getPostsByCategorySlugs(["business", "motoring", "tech-talk"], 4),
    getPostsByCategorySlugs(
      ["feature", "features", "entertainment", "lifestyle", "health"],
      4,
    ),
    getPostsByCategorySlugs(["initiatives"], 4),
  ]);

  // Merge all nav posts, deduplicated — each category is guaranteed representation
  const navPosts = [
    ...recentNav,
    ...sportsNav.posts,
    ...voicesNav.posts,
    ...businessNav.posts,
    ...featuresNav.posts,
    ...initiativesNav.posts,
  ].filter((p, i, arr) => arr.findIndex((x) => x.id === p.id) === i);

  // Latest local+featured post for breaking news, fallback to any featured
  const breakingPost =
    posts.find((p) => p.data.subcategory === "local" && p.data.is_featured) ||
    posts.find((p) => p.data.is_featured) ||
    posts[0] ||
    null;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Runs synchronously before React — blocks page on first visit with no flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{if(!sessionStorage.getItem('dg_intro'))document.documentElement.classList.add('dg-first-load')}catch(e){}`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        {/* Google AdSense — auto ads */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1002683760929339"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-FTDWF3L7Z8"
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-FTDWF3L7Z8');
        `}</Script>
        <LoadingScreen />
        <AutoRefresh intervalMs={60_000} />
        <Header posts={posts} breakingPost={breakingPost} />
        <NavigationBar navPosts={navPosts} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
